//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.Analyzer.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDo.Analyzer.Helpers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every line must consist of less than {1} characters..
        /// </summary>
        internal static string LineLengthDescription {
            get {
                return ResourceManager.GetString("LineLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line &quot;{0}&quot; exceeds the {1} character limit..
        /// </summary>
        internal static string LineLengthMessageFormat {
            get {
                return ResourceManager.GetString("LineLengthMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines should not exceed {1} characters..
        /// </summary>
        internal static string LineLengthTitle {
            get {
                return ResourceManager.GetString("LineLengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every if statement should use curly braces..
        /// </summary>
        internal static string OneLinerIfReturnDescription {
            get {
                return ResourceManager.GetString("OneLinerIfReturnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The if statement does not use curly braces..
        /// </summary>
        internal static string OneLinerIfReturnMessageFormat {
            get {
                return ResourceManager.GetString("OneLinerIfReturnMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If statements use curly braces..
        /// </summary>
        internal static string OneLinerIfReturnTitle {
            get {
                return ResourceManager.GetString("OneLinerIfReturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit tests should begin with the &quot;When&quot; word..
        /// </summary>
        internal static string XUnitAnalyzerDescription {
            get {
                return ResourceManager.GetString("XUnitAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name &quot;{0}&quot; does not begin with the &quot;When&quot; word..
        /// </summary>
        internal static string XUnitAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("XUnitAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit tests begin with the &quot;When&quot; word..
        /// </summary>
        internal static string XUnitAnalyzerTitle {
            get {
                return ResourceManager.GetString("XUnitAnalyzerTitle", resourceCulture);
            }
        }
    }
}
